build: Link with libdl when linking with libcrypto is required.
On lots of systems libcrypto is linked with libdl, because libcrypto
dynamically loads executable objects. Without -ldl on the linker command
line the linking phase fails with:

/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x5c): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x100): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x154): undefined reference to `dlerror'